### ISSUE TITLE
Pint import failing on Azure test pipeline

### ISSUE THREAD

**Issue by MaxxRe2** [hgrecco/pint#1553]
My Azure test pipelines have been failing during the pint module import.

The exception is (example for Python 3.8 for output of one script, but it's the same message for all Python versions and scripts using `pint`):
```
 from pint import Quantity
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/Pint-0.19.2-py3.8.egg/pint/__init__.py:30: in <module>
    ???
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/Pint-0.19.2-py3.8.egg/pint/registry.py:69: in <module>
    ???
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/Pint-0.19.2-py3.8.egg/pint/parser.py:21: in <module>
    ???
E   ModuleNotFoundError: No module named 'pint._vendor'
```

I had `pint` on my `requirements.txt`. On my local machine it works just fine. I figured out specifying (and thus reverting) the version to `pint==18.0` resolves the error.

The configuration of the Azure Agent is:

```
pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
  displayName: 'Upgrade pip'
  
- script: |
    python -m pip install keyring artifacts-keyring
  displayName: 'Install keyring artifacts-keyring'

- script: |
    pip install my-own-package-from-my-own-feed
  displayName: 'Install own module'

- script: |
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
  displayName: 'pytest'
```
It failed for 3.8 and 3.9.

Not sure what the underlying issue is.
